using System.Reflection;
using Microsoft.EntityFrameworkCore;
using MillerDemo.Application.Persistence;
using MillerDemo.Domain.DnsRecords.Entities;
using MillerDemo.Domain.Jobs.Entities;

namespace MillerDemo.Infrastructure.Persistence;

/// <summary>
/// Represents an SQL server database context.
/// </summary>
public partial class SqlServerDbContext(DbContextOptions options) : DbContext(options), IApplicationDbContext
{
    /// <inheritdoc/>
    public virtual DbSet<DnsRecord> DnsRecords => Set<DnsRecord>();

    /// <inheritdoc/>
    public virtual DbSet<Job> Jobs => Set<Job>();

    /// <inheritdoc/>
    public new async Task SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        await base.SaveChangesAsync(cancellationToken);
    }

    /// <inheritdoc/>
    public Task MigrateAsync(CancellationToken cancellationToken = default)
    {
        return base.Database.MigrateAsync(cancellationToken);
    }

    /// <inheritdoc/>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_100_CI_AI_SC_UTF8");
        modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());

        // ReSharper disable once InvocationIsSkipped
        // Code-generated by Entity Framework
        OnModelCreatingPartial(modelBuilder);
    }

    // ReSharper disable once PartialMethodWithSinglePart
    // Code-generated by Entity Framework
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}